<!DOCTYPE html>
<html>
<body>

<h1>Submit your Relatives Information</h1>
<form action="insert.php" method="post">
    Value1: <input type="text" name = "Name" /><br/>
    Value2: <input type="text" name = "Birth Month" /><br/>
    Value3: <input type="text" name = "Birth Year" /><br/>
    Value4: <input type="text" name = "Passed Month" /><br/>
    Value5: <input type="text" name = "Passed Year" /><br/>
    <input type="submit" />
</form>
<p>Submit your relative/family member's information above. A valid email address is required for verification of information if we are unable to locate the it in any public records.</p>

</body>
</html>
